"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IpcChannel = void 0;
var IpcChannel;
(function (IpcChannel) {
    IpcChannel["PROJECTS_GET_ALL"] = "projects:getAll";
    IpcChannel["PROJECTS_CREATE"] = "projects:create";
    IpcChannel["PROJECTS_GET_ONE"] = "projects:getOne";
    IpcChannel["PROJECTS_UPDATE"] = "projects:update";
    IpcChannel["PROJECTS_DELETE"] = "projects:delete";
    IpcChannel["PROJECTS_GET_SEARCH_HISTORY"] = "projects:getSearchHistory";
    IpcChannel["SEARCH_EXECUTE"] = "search:execute";
    IpcChannel["SEARCH_TRANSLATE_QUERY"] = "search:translateQuery";
    IpcChannel["SEARCH_REVERT"] = "search:revert";
    IpcChannel["ARTICLES_GET_BY_PROJECT"] = "articles:getByProject";
    IpcChannel["ARTICLES_GET_ONE"] = "articles:getOne";
    IpcChannel["ARTICLES_UPDATE_STATUS"] = "articles:updateStatus";
    IpcChannel["HIGHLIGHTS_GET"] = "highlights:get";
    IpcChannel["HIGHLIGHTS_CREATE"] = "highlights:create";
    IpcChannel["ANNOTATIONS_GET"] = "annotations:get";
    IpcChannel["ANNOTATIONS_CREATE"] = "annotations:create";
    IpcChannel["ANNOTATIONS_UPDATE"] = "annotations:update";
    IpcChannel["ANNOTATIONS_DELETE"] = "annotations:delete";
    IpcChannel["HIGHLIGHTS_DELETE"] = "highlights:delete";
    IpcChannel["PDF_UPLOAD"] = "pdf:upload";
    IpcChannel["PDF_GET"] = "pdf:get";
    IpcChannel["PDF_UNLINK"] = "pdf:unlink";
    IpcChannel["ARTICLES_CREATE_MANUAL"] = "articles:createManual";
    IpcChannel["EXPORT_CSV"] = "export:csv";
    IpcChannel["EXPORT_BIBLIOSHINY"] = "export:biblioshiny";
    IpcChannel["DIALOG_OPEN_FILE"] = "dialog:openFile";
    IpcChannel["SETTINGS_GET"] = "settings:get";
    IpcChannel["SETTINGS_SET"] = "settings:set";
    IpcChannel["DIARY_GET_ALL"] = "diary:getAll";
    IpcChannel["DIARY_GET_ONE"] = "diary:getOne";
    IpcChannel["DIARY_SAVE"] = "diary:save";
    IpcChannel["DIARY_DELETE"] = "diary:delete";
    IpcChannel["APP_GET_VERSION"] = "app:getVersion";
})(IpcChannel || (exports.IpcChannel = IpcChannel = {}));
